use crate::isa::Operand;

#[derive(Debug)]
pub enum Op {
    Nop,
    Cli,
    Sti,
    Std,
    Cld,
    Lea { src: Operand, dst: Operand },
    Jnz { addr: Operand },
    Jz { addr: Operand },
    Jmp { addr: Operand },
    Jnc { addr: Operand },
    Inc { dst: Operand },
    Dec { dst: Operand },
    Not { dst: Operand },
    Neg { dst: Operand },
    Rol { dst: Operand, count: u8 },
    Ror { dst: Operand, count: u8 },
    Rcl { dst: Operand, count: u8 },
    Rcr { dst: Operand, count: u8 },
    Shl { dst: Operand, count: u8 },
    Sal { dst: Operand, count: u8 },
    Shr { dst: Operand, count: u8 },
    Sar { dst: Operand, count: u8 },
    Test { op1: Operand, op2: Operand },
    Mov { src: Operand, dst: Operand },
    Sub { src: Operand, dst: Operand },
    Add { src: Operand, dst: Operand },
    Adc { src: Operand, dst: Operand },
    Mul { src: Operand },
    IMul { src: Operand },
    Div { src: Operand },
    IDiv { src: Operand },
    Xor { src: Operand, dst: Operand },
    JmpFar { segment: u16, offset: u16 },
    Int(u8),
    Call { addr: Operand },
    MovSb { rep: bool },
    MovSw { rep: bool },
    Push { src: Operand },
    Pop { dst: Operand },
    Cmp { dst: Operand, src: Operand },
    Ret,
    Halt,
}
