use crate::isa::Operand;

#[derive(Debug)]
pub enum Op {
    Nop,
    Cli,
    Sti,
    Std,
    Cld,
    Lea { src: Operand, dst: Operand },
    Jnz { addr: Operand },
    Jz { addr: Operand },
    Jmp { addr: Operand },
    Inc { dst: Operand },
    Test { op1: Operand, op2: Operand },
    Mov { src: Operand, dst: Operand },
    Sub { src: Operand, dst: Operand },
    Add { src: Operand, dst: Operand },
    Adc { src: Operand, dst: Operand },
    Xor { src: Operand, dst: Operand },
    JmpFar { segment: u16, offset: u16 },
    Int(u8),
    Call { addr: Operand },
    MovSb { rep: bool },
    MovSw { rep: bool },
    Push { src: Operand },
    Pop { dst: Operand },
    Ret,
    Halt,
}
